name: build and deploy frontend

on:
  push:
    paths:
    - '.github/workflows/frontend.yml'
    - 'demo/**'
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      working-directory: ./demo
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: "10.x"
    - name: install using npm install
      run: npm install
      working-directory: ${{ env.working-directory }}
    - name: build
      run: npm run build_github
      working-directory: ${{ env.working-directory }}
    - name: copy 404.html
      run: |
        cd ${{ env.working-directory }}/dist
        cp index.html 404.html
    - name: deploy github page
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.PAGE_TOKEN }}
        publish_dir: ${{ env.working-directory }}/dist
        force_orphan: true
