name: build and deploy frontend

on:
  push:
    paths:
    - '.github/workflows/frontend.yml'
    - 'demo/**'
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      working-directory: ./demo
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: "10.x"
    - name: install using npm install
      run: npm install
      working-directory: ${{ env.working-directory }}
    - name: build
      run: npm run build_github
      working-directory: ${{ env.working-directory }}
    - name: copy 404.html
      run: |
        cd ${{ env.working-directory }}/dist
        cp index.html 404.html
    - name: deploy github page
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.PAGE_TOKEN }}
        publish_dir: ${{ env.working-directory }}/dist
        force_orphan: true
  compile:
    needs: deploy
    runs-on: ubuntu-latest
    env:
      path-master: master
      path-gh-pages: gh-pages
      report-working-directory: report
      root-file-name: report
    steps:
      - name: Set up master repository
        uses: actions/checkout@v2
        with:
          ref: master
          path: ${{ env.path-master }}
      - name: Set up gh-pages repository
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: ${{ env.path-gh-pages }}
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: ./${{ env.path-master }}/${{ env.report-working-directory }}
          root_file: ${{ env.root-file-name }}.tex
      - name: copy pdf file to data directory
        run: |
          cp ./${{ env.path-master }}/${{ env.report-working-directory }}/${{ env.root-file-name }}.pdf ./${{ env.path-gh-pages }}/${{ env.root-file-name }}.pdf
      - uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PAGE_TOKEN }}
          publish_dir: ./${{ env.path-gh-pages }}
          force_orphan: true
