name: compile the latex file

on:
  push:
    paths:
    - 'report/**'
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      working-directory: ./report
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: ${{ env.working-directory }}
          root_file: proposal.tex
